# Generated by Django 4.2.6 on 2023-12-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(max_length=10000)),
                ('likes', models.PositiveIntegerField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
